name: MVLM
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - cudatoolkit=11.1
  - numpy
  - pytorch
  - torchvision
  - torchaudio
  - matplotlib
  - imageio
  - scipy
  - scikit-image
  - absl-py
  - libnetcdf
  - vtk
  - tensorboard